In [2]:
#1) way say we have model and we train the model with all the data set and test it the model will predict the values accurately bcoz it has seen the data previously
#2) way say we have 100 data sets and we are training thee model with 80% of the data and remaining 20% is used for testing it is good but not perfect
#3)K fold cross validation say we take 100 samples in that we divide it into 5 say each contains 25% of data first time we train 2,3,4 and test 1.next time we test with 2and train with 1,3,4,5 same for all the box each one time testing and at last we take the average of all the score in this way we are training the model with all the type of data
#we can't train the model once and say this or that model is best becauseeacjh time we run the model the dataset chamges means the the score value of the model % increase so it is not good way

In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits=load_digits()

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.3)

In [5]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [7]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [ ]:
#here the first matrix is used for trainning and the second matrix is used for testing here the 012 is in testing then it is added to training similarly 